### ISSUE TITLE
Zooming?

### ISSUE THREAD

**Issue by brandon-kohn** [awulkiew/graphical-debugging#1]
Are there any plans to add zooming?

**Comment by awulkiew** [comment]
Indeed, zooming and moving would be a good addition. I was thinking about it but I don't plan to add it in the near future due to lack of free time.

**Comment by brandon-kohn** [comment]
I hacked in a (sloppy) mechanism on my fork which allows me to zoom. Good enough for my uses.

**Comment by mloskot** [comment]
@brandon-kohn I'd submit a PR

**Comment by robiwano** [comment]
The zooming part is only in 2D views ? I'd like to have dynamic drawing and zooming in the 1D view also...

**Comment by awulkiew** [comment]
There is no zooming code in the "official" release, it's in fork only.

**Comment by awulkiew** [comment]
@brandon-kohn I added zooming (or rather cropping) in the develop branch together with some other navigation improvements like scales and coordinates under mouse cursor. It looks like this:

Before:

![before](https://user-images.githubusercontent.com/1226951/45270382-38c37980-b49d-11e8-8b28-b85bcff8d558.png)

After:

![after](https://user-images.githubusercontent.com/1226951/45270394-5abcfc00-b49d-11e8-8098-d552ed2900cc.png)

**Comment by awulkiew** [comment]
Added in version 0.11.
