### ISSUE TITLE
Visual Studio Code Support?

### ISSUE THREAD

**Issue by davidcrawford** [awulkiew/graphical-debugging#13]
Hi Adam, this project looks very interesting!  Have you looked into what it would take to make this work inside Visual Studio Code?  Do you know if anyone is working on something similar for that IDE?

**Comment by awulkiew** [comment]
Hi David, no I haven't and according to my knowledge this would not be possible in VS Code. I may be wrong of course. I don't know if that helps but this extension works with VS Community.
