### ISSUE TITLE
Several plot watch windows 

### ISSUE THREAD

**Issue by tommycarlsson** [awulkiew/graphical-debugging#14]
Hi Adam,
Is it possible to open several plot watch windows or split the current plot watch into several horizontal sections? This would be a very nice feature if it's not possible today.

**Comment by awulkiew** [comment]
Hi Tommy,
No, it's not possible to have several windows. But I think that's a good idea.

**Comment by tommycarlsson** [comment]
Can you contact me directly by mail?

**Comment by awulkiew** [comment]
@tommycarlsson sure. Btw, you can also find me at https://gitter.im/boostorg/geometry and chat there.

**Comment by awulkiew** [comment]
@tommycarlsson I added it in v0.28. Please let me know if it works for you so I can close the issue.

**Comment by tommycarlsson** [comment]
It works, thank you very much!
