### ISSUE TITLE
Advanced display capabilities

### ISSUE THREAD

**Issue by kjaft** [awulkiew/graphical-debugging#15]
Hi. Very handy tool! It would be very nice if there was some additional functionality:

1. A checkbox (or similar) to temporarily disable display of a watch, without having to remove/re-add it
2. Color choice for each watch

Thanks!

**Comment by awulkiew** [comment]
Yes, these are good suggestions. Thanks!

**Comment by awulkiew** [comment]
We're talking about the PlotWatch and GeometryWatch, correct?
Or would you like to have these also in GraphicalWatch?

**Comment by kjaft** [comment]
Yes exactly, PlotWatch and GeometryWatch. I have to confess I hardly used GraphicalWatch yet.

**Comment by awulkiew** [comment]
Added in v0.32.
