### ISSUE TITLE
How to add user type without points in sequence as std::vector

### ISSUE THREAD

**Issue by Ok23** [awulkiew/graphical-debugging#18]
Example:
class Rect
{
	float left, top, width, height;
}

**Comment by awulkiew** [comment]
Not possible currently without forking the extension and adding in the code. I'll treat it as a feature request.

**Comment by awulkiew** [comment]
Added in 0.32 though have in mind that the origin of the coordinate system is in the bottom left corner. If in your coordinate system the origin is in the top left corner then for now you can define `top` as `bottom` and live with the fact that it's upside down.
