### ISSUE TITLE
Add support for eigen data types

### ISSUE THREAD

**Issue by rconde01** [awulkiew/graphical-debugging#2]
...title says it all

http://eigen.tuxfamily.org/index.php?title=Main_Page

They have regular visualizers already so that could probably be built off of...

**Comment by awulkiew** [comment]
Which data types do you have in mind and how should they be visualized? Are you speaking about Vectors which are typedefs of Matrix<type, N, 1> and could represent points? Or do you have something else in mind?

**Comment by rconde01** [comment]
I guess there are a few options:
- VectorXd could be plotted with the index as the x axis
- Matrix<double,N,M> could be plotted as M independent series, or x/y pairs...or x,y1,y2,y3, or reversing

**Comment by awulkiew** [comment]
Ok, AFAIU you don't expect to represent points with Vectors. Though this would probably be my preference print vectors as points and matrices as column vectors so sets of points or multipoints. But I don't know if this would be useful in general case.

What do you mean by "plotted with the index as the x axis"? Maybe you could draw some picture?

FYI, I won't have time to do it in the near future. So you could also consider forking the repo and playing with it yourself if that's something you really need right now. Here is probably the place where VectorXd should be loaded from the debugger: https://github.com/awulkiew/graphical-debugging/blob/develop/Visual_Studio_2015/GraphicalDebugging/ExpressionDrawer.cs#L1004

**Comment by awulkiew** [comment]
@rconde01 Is this issue still relevant? You haven't answered my question about your expectations regarding the presentation of Vector and Matrix data.

**Comment by awulkiew** [comment]
It is possible to define user point types since v0.25 and other geometries since v0.29. So this issue should be covered as well. Closing.
