### ISSUE TITLE
Bug: Visual Studio locks up when trying to view a std::vector<int>

### ISSUE THREAD

**Issue by robiwano** [awulkiew/graphical-debugging#3]
In GraphicalWatch, if I add a std::vector<int> variable, the IDE locks up and needs to be killed via task manager.

**Comment by robiwano** [comment]
same happens with std::vector<float>...

**Comment by awulkiew** [comment]
May the reason be that there are many elements in the vector so parsing all of them takes time? Does the same happen for shorter vectors?

**Comment by robiwano** [comment]
I've debugged it and indeed it is the parsing of v[0]...v[n-1], so I'm now modifying the code to work with raw pointers instead, should increase speed by several magnitudes.

**Comment by robiwano** [comment]
Will setup a fork of it, if you'd like to review the code later on.

**Comment by awulkiew** [comment]
Sure, I'll gladly review improvements.

The problem will still remain though, i.e. it would be possible to find a vector so big that the IDE would hang. I was considering going around it by:
  - measuring the time and giving a user an option to stop after e.g. 10s
  - after some time draw only part of the data if the parsing takes too long
  - speeding up the parsing of data by doing it in multiple threads (though this also won't solve the general problem)
  - accessing the debugger and parsing asynchroniously form another therad periodically updating the presentation or showing some animation on the drawing, so allowing the user to perform actions at the same time (I'm not sure if that's possible with the debugger API).

But maybe you have some other idea which could solve it?

**Comment by robiwano** [comment]
I will do direct conversion of pointer data via unsafe{} code, so as long as the plotting parts are happy with it, there won't be any problems even with very large vectors. But anyway, threaded update of the plot would not be a bad thing.

Btw, does this extension re-evaluate the expressions upon hitting a breakpoint ?

**Comment by robiwano** [comment]
I've managed to read out the vector data as a byte array (via this method: https://www.codeproject.com/Articles/670373/Csharp-Read-Write-another-Process-Memory), so now it's as fast as it can be. However, the plotting is a bit scarce :) (i.e. I'd need a bigger window showing the vector data and be able to zoom in it, maybe also setting colors per vector etc. etc.)

**Comment by awulkiew** [comment]
Then I'd argue that you need something more like GeometryWatch than GraphicalWatch as is currently implemented. A window allowing to draw multiple 1d plots in the same coordinate system, possibly with different colors and styles. PlotWatch?

**Comment by robiwano** [comment]
Sounds reasonable :)

**Comment by awulkiew** [comment]
@robiwano I added Plot Watch with zoom recently (ver 0.12) so you can experiment with it. Currently it displays values as bars but you could change it here easily, e.g. to points or lines: https://github.com/awulkiew/graphical-debugging/blob/v0.12/Visual_Studio_2015/GraphicalDebugging/ExpressionDrawer.cs#L591

**Comment by awulkiew** [comment]
@robiwano I implemented direct memory access as you suggested though probably not the same way. For now only for contiguous containers like `std::vector`, `boost::container::vector`, `std::array`, etc. storing fundamental data types: `double`, `float`, `int`, etc. So e.g. loading of 10000 element vector takes around 1sec instead of 15sec. Enabled by default, can be disabled in options. Pushed to develop so you can play with it. Will be released in ver 0.15.

**Comment by robiwano** [comment]
Nice, does it work with 64-bit applications aswell ? Since my last post, I did a PlotWatch using OxyPlot for plotting, which has everything needed for zooming. Also I made a 64 bit .exe to get direct memory access for 64 bit processes, using std i/o back into the PlotWatch.

**Comment by robiwano** [comment]
Ah, very neat with the memory reading.
