### ISSUE TITLE
Wait popup non-blockable

### ISSUE THREAD

**Issue by cdcseacave** [awulkiew/graphical-debugging#30]
The wait popup whenever there is a large geometry to be displayed is very annoying; would be very helpful a way to disable it or at least make that popup window not blockable and let the thread continue to process while it is open and waiting an input from the user; in case that happens first it will just auto close it too

**Comment by awulkiew** [comment]
Good idea.

If you're really annoyed you can build your own version of the extension after commenting out this section:
https://github.com/awulkiew/graphical-debugging/blob/v0.32/Visual_Studio_2017/GraphicalDebugging/ExpressionLoader_Util.cs#L27-L47
