### ISSUE TITLE
reference type not supported

### ISSUE THREAD

**Issue by tangketan** [awulkiew/graphical-debugging#39]
I have a user-defined point type "Point" and it's displayed fine. But a reference to Point is not displayed. E.g.
    Point p(100,100);  // p is displayed OK
    Point& pr=p;       // pr is not shown
Anyone know any solution? Thanks!

**Comment by tangketan** [comment]
Sorry for the late reply. I'm using version 0.33, which should be the latest. The Point type itself is OK. I encountered problems when it's a member variable of a class. It seems whether a member variable can be shown depends on its owner's state. 
Attached is a minimal working example plus the config XML file.
![image](https://user-images.githubusercontent.com/13730459/222108138-8807e17a-699d-4422-afab-41fc4cd78279.png)

**Comment by awulkiew** [comment]
Support added in version 0.51
