### ISSUE TITLE
Add ability to define x and y points

### ISSUE THREAD

**Issue by terranjp** [awulkiew/graphical-debugging#4]
It would be nice to be able to be able to plot independent x and y values  in the Plot Watch similar to [ArrayPlotter](https://marketplace.visualstudio.com/items?itemName=RodneyThomson.ArrayPlotter).

For example I have `std::vector<double> x` and `std::vector<double> y`. I am currently creating a `std::vector<std::pair<double, double>>` from to the two vectors but it would be nice to be able to use the data structures in place.

**Comment by awulkiew** [comment]
For this I'd have to think about the syntax for watch list element. Maybe semicolon could be used to separate data for separate dimensions (comma is already used to define size of c-array). So something like this: `vec_x;vec_y` and then also `array_x,100;array_y,100`. Unless you have some other idea?

But out of curiosity. Why are you storing coordinates in different arrays? From data-driven development it'd have sense if you knew that you frequently access coordinates of one dimension at a time, to separate hot and cold data and prevent cache misses. Is that the case here?

**Comment by terranjp** [comment]
That syntax seems fine to me. I am using different arrays because it is simplifies my algorithm, and the arrays are bound to Python Numpy arrays via Pybind11, it's just easier to keep them in separate arrays.

**Comment by awulkiew** [comment]
@terranjp I added it in v0.22: https://github.com/awulkiew/graphical-debugging/releases/tag/v0.22
Could you check it out?

**Comment by terranjp** [comment]
Unfortunately I couldn't get it to work. It acts like there is no data present. I tried the following simple data structures:
```
        vector<double> y{ 0, -100, -350, -100 };
	vector<double> x{ 0, 100, 200, 300 };
```

And then `x;y` in the Name column of the graphical debugger. 

Did I miss something?

**Comment by awulkiew** [comment]
No, it should work like this in all watch windows. In Graphical Watch by default it should display the containers as a container of points or multi-point.

I tried to reproduce the problem on x64 OS with community versions of VS2015 (x86) and VS2017 (x86 and x64) in debug mode. But it works for me.

Is there something specific about your configuration? What's your VS version, etc.

Have you checked if your extension is updated to version 0.22?

**Comment by awulkiew** [comment]
BTW, is the type correctly displayed? It should be something like:

    std::vector<double> ; std::vector<double>
