### ISSUE TITLE
Port to VS Code

### ISSUE THREAD

**Issue by TrackerSB** [awulkiew/graphical-debugging#40]
How hard would it be to port this plugin for VS Code?
Both MSVS and VS Code use the VSIX format and both use the Debug Adapter Protocol Interface.

**Comment by nbwuzhe** [comment]
Hi @awulkiew Thanks a lot for this useful tool. I'm also interested in porting it to VS Code since this is my most frequently used platform. Just curious whether it is difficult for the array plotting part to be converted to VS code extensions?

**Comment by mloskot** [comment]
@nbwuzhe  
> Just curious whether it is difficult for the array plotting part to be converted to VS code extensions?

I'd start with search for existing solutions, for example, https://marketplace.visualstudio.com/items?itemName=hediet.debug-visualizer and read the code, and compare with this implementation for the big VS.
It's not difficult. It just needs time investment.

**Comment by awulkiew** [comment]
@nbwuzhe I'm working on it right now in my free time. I have all building blocks figured out and am currently working on supporting user-defined containers like vector. When I have some basic version ready I'll make the repo public and release it.

I'm also waiting for a response for my [issue at MIEngine](https://github.com/microsoft/MIEngine/issues/1236). My primary concern is C++ and various debuggers may be used with VSCode. There is a problem with VSCode and GDB (maybe LLVM too I haven't checked). If a variable defined with typedef is debugged with GDB the type of variable returned with DAP is the name of the typedef, not the original type. This is also why MSVC natvis files may not work with VSCode and GDB. There are some issues about this at vscode-cpptools. If my issue at MIEngine is addressed then it should at least allow me to work around this. Without solving it such extension doesn't make sense for C++.

**Comment by nbwuzhe** [comment]
> @nbwuzhe
> 
> > Just curious whether it is difficult for the array plotting part to be converted to VS code extensions?
> 
> I'd start with search for existing solutions, for example, https://marketplace.visualstudio.com/items?itemName=hediet.debug-visualizer and read the code, and compare with this implementation for the big VS. It's not difficult. It just needs time investment.

Hi Mateusz, thanks for your information. To be honest I tried that visualizer but it seems not to work at all for C++: only the first element of the array/vector is showing. I looked into the Issues of that repo with a similar report from the other users, but unfortunately, the author replied that he was not familiar with Cpp and could not help much.

**Comment by nbwuzhe** [comment]
> @nbwuzhe I'm working on it right now in my free time. I have all building blocks figured out and am currently working on supporting user-defined containers like vector. When I have some basic version ready I'll make the repo public and release it.
> 
> I'm also waiting for a response for my [issue at MIEngine](https://github.com/microsoft/MIEngine/issues/1236). My primary concern is C++ and various debuggers may be used with VSCode. There is a problem with VSCode and GDB (maybe LLVM too I haven't checked). If a variable defined with typedef is debugged with GDB the type of variable returned with DAP is the name of the typedef, not the original type. This is also why MSVC natvis files may not work with VSCode and GDB. There are some issues about this at vscode-cpptools. If my issue at MIEngine is addressed then it should at least allow me to work around this. Without solving it such extension doesn't make sense for C++.

Thanks for the detailed info. Currently I'm doing remote debugging using my Windows PC on a Linux server and it is easy to achieve with VS Code with SSH-Remote extension, however, Visual Studio 2019 is not supporting this way, and that's why I'm seeking to have your useful tool to be extended to VS Code. I'm trying to grab up your code in this repo to see how to help, but it might take some time. Thanks a lot for your efforts!

**Comment by mloskot** [comment]
> it is easy to achieve with VS Code with SSH-Remote extension, however, Visual Studio 2019 is not supporting this way

FYI, if your project is CMake-based, then remote debugging a program on Linux machine is also easy to configure:
https://docs.microsoft.com/en-us/cpp/build/configure-cmake-debugging-sessions?

**Comment by awulkiew** [comment]
@nbwuzhe The extension for vscode is going to be different than this one, written in typescript, not in C#, using different APIs, etc. So it is not a port of this extension but another one written from scratch. I have it in a different repo which is currently private. As Mateusz said, it's best to search GitHub for extensions for vscode that are communicating with the debugger to see how this may be done. There are of course official references of APIs too.

While debugging remotely which debugger are you using?

**Comment by awulkiew** [comment]
@TrackerSB @nbwuzhe @mloskot
I have developed the first version: https://github.com/awulkiew/graphical-debugging-vscode
As I mentioned typedefs doesn't work with GDB. If my issue is addressed at MIEngine I'll be able to work around it.
We can move the discussion there.

**Comment by nbwuzhe** [comment]
> @TrackerSB @nbwuzhe @mloskot I have developed the first version: https://github.com/awulkiew/graphical-debugging-vscode We can move the discussion there. As I mentioned typedefs doesn't work with GDB. If my issue is addressed at MIEngine I'll be able to work around it.

That's wonderful! Can't imaging that you done that so quick. Will give a test and give feedback.

And sorry for late reply, I'm using cppdbg while doing remote debugging.

**Comment by mloskot** [comment]
Indeed, you've been amazingly quick, kudos!
Since I use VS Code heavily, I will try to try your extension out!
