### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by duken72** [awulkiew/graphical-debugging#43]
Hi,

I have some problem with adding the extension to VS Code.
- I couldn't find the package in VS Code market place (Ctrl+Shift+X in VS Code, then search)
- I tried to download .vsix file from the website (marketplace.visualstudio.com) and install, but VS Code give error message:
`extension/package.json not found inside zip.`

**Comment by awulkiew** [comment]
This extension doesn't work with VSCode but with "regular" VS.
For VSCode go here:
https://github.com/awulkiew/graphical-debugging-vscode
The releases are here:
https://github.com/awulkiew/graphical-debugging-vscode/releases
You don't have to unpack anything. When you want to install a VSIX in VSCode you have to open extensions, click `...` and pick "Install from VSIX". I'm planning to release it at markeplace in the near future.
