### ISSUE TITLE
Support for Visual Studio 2019

### ISSUE THREAD

**Issue by MicBe** [awulkiew/graphical-debugging#5]
Any plan to support VS 2019?

I followed the following procedure to modify .vsix to add support for VS 2019 but apparently it's not enough:
https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/

I get this error message:
"This extension cannot be installed because tje following references are missing: Microsoft.VisualStudio.Component.CoreEditor"

Thanks!

**Comment by awulkiew** [comment]
Just checked it out and it works for me. Could you try to install it?
https://github.com/awulkiew/graphical-debugging/releases/tag/v0.21

**Comment by MicBe** [comment]
It's working for me too, thank you!
