### ISSUE TITLE
Plot Watch does not draw the graphs if 'Hexadecimal Display' is enabled

### ISSUE THREAD

**Issue by gtrainavicius** [awulkiew/graphical-debugging#6]
Just noticed that Plot Watch stopped working, even though it used to work just fine a couple of days back. I tried many things to get it working again, in the end, what did the trick, was disabling the 'Hexadecimal Display' option in the right click menu of VS's Watch window, and resetting or editing the watched values in Plot Watch window.

**Comment by awulkiew** [comment]
Thanks for the info.
What VS version do you use?
For which type does it fail?
Is my understanding correct that it worked before with hexadecimal display enabled?

**Comment by awulkiew** [comment]
I was able to reproduce it with vs2015 for `std::vector<int>`.
The error message for me is `Input string was not in a correct format`. Is it the same for you?

**Comment by gtrainavicius** [comment]
Yes, I have seen this message displayed, tried swapping from std::vector<uint8_t> to float, the message was not displayed, and nothing was drawn, except for the '+' indicating the mouse position.

I'm using VS2017.

**Comment by awulkiew** [comment]
It should be fixed in version 0.25 (https://github.com/awulkiew/graphical-debugging/releases/tag/v0.25).
Could you please check it out?
I'll also upload it to VS marketplace so it will update automatically.

**Comment by gtrainavicius** [comment]
Just tried it out, it fixed this issue. Cheers!

**Comment by awulkiew** [comment]
Thanks for reporting!
