### ISSUE TITLE
Support for VS pre 2022

### ISSUE THREAD

**Issue by Murkas94** [awulkiew/graphical-debugging#62]
Hi there,

First of all: Thanks for this awesome project, it works great and is realy helpful!

Unfortunatly i am still stuck with VS2019 but needed features which were introduced with v0.5+.
Since i am not experienced enaugh with VS project files and compatibilty between pre-VS2022 and VS2022, i don't see a way to get both working at the same time. Still, i wanted those features, so i [forked your repo](https://github.com/Murkas94/graphical-debugging-pre-vs2022) and backported [each tag/release](https://github.com/Murkas94/graphical-debugging-pre-vs2022/releases) to pre-VS2022.

I don't want to claim anything for me, but as this could be helpful for others, maybe it could be mentioned somewhere on the Readme?

Best regards,
Markus

**Comment by awulkiew** [comment]
Hi Markus,
Thanks for taking the time and sharing the backported extension with others. I added the info to the readme in "Supported Versions" section. I hope it's fine.

**Comment by Murkas94** [comment]
Sure, it is fine. Thanks!
