### ISSUE TITLE
Is development supported using VS 2017 or 2019?

### ISSUE THREAD

**Issue by mloskot** [awulkiew/graphical-debugging#7]
The [Build](https://github.com/awulkiew/graphical-debugging/tree/c7231ae2ea5b98cc9e13247bcb472f46bc017214#build) section in current README says:

> You need Microsoft Visual Studio 2015 Update 3, .NET Framework 4.5.2 and Visual Studio 2015 SDK.

Does it mean a minimal VS version or exact VS version required?

Is it possible to develop and build the extension using VS 2017 or 2019?

------

Sorry, but I didn't find a better place to ask questions about the extension development.

**Comment by awulkiew** [comment]
It means that this exact version is required. I didn't try to use different one. I think you'd have to convert the project to VS2017, just like @JloveU has done in his fork (https://github.com/JloveU/graphical-debugging/commits/master) or create the project from scratch.

**Comment by mloskot** [comment]
That makes sense, thanks.
